apiVersion: v1
kind: Service
metadata:
  name: {{ include "unleash-devops-app.fullname" . }}
  labels:
    app: {{ include "unleash-devops-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ include "unleash-devops-app.name" . }}
