name: CI Pipeline

on:
  push:
    branches:
    - master

jobs:
  build:
    # Use a Windows runner if you prefer, but Linux runners work perfectly too.
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Docker Build
      run: docker build -t yonatansinay2020/my-devops-app:${{ github.sha }} .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push yonatansinay2020/my-devops-app:${{ github.sha }}
